### PR TITLE
Let users know which props changed (without looping)

### PR DESCRIPTION
**Pull request by trusktr**
_If there is a linked issue, mention it here._

* [ ] Bug
* [x] Feature, https://github.com/skatejs/skatejs/issues/1318

## Requirements

* [x] Read the
      [contribution guidelines](https://github.com/skatejs/skatejs/blob/5.x/CONTRIBUTING.md).
* [ ] Wrote tests.
* [ ] Updated docs and upgrade instructions, if necessary.
* [ ] Updated TS definitions, if necessary.

## Rationale

_Why is this PR necessary?_

It gives the user a simple array to check which props were changed. This may prevent someone from instead relying on `attributeChangedCallback` which is not batched.

The user can then _optionally_ loop on the changed attributes.

## Implementation

_Why have you implemented it this way? Did you try any other methods?_

I user an `Array` isntead of a `Set` because I didn't want to worry about TypeScript types, and plus it's probably faster. I'm setting `length = 0` instead of making a new array (avoiding GC).

## Open questions

_Are there any open questions about this implementation that need answers?_

Not yet.

## Tasks

_List any tasks you need to do here, if any. Delete this section if you don't
need it._

* [ ] If you're okay with the change, then I can finish the Requirements section (docs, tests, etc).

### CODE REVIEW

**Comment by treshugart** [comment]
> This may prevent someone from instead relying on attributeChangedCallback which is not batched.

It is batched in terms of only happening after all set attribute calls happen in a microtask, but is called for every set.

You say:

> without looping

However, `array.includes()` is essentially a `array.indexOf() > -1` alias, and the algorithmic complexity of `indexOf()`, I believe, is O(log n). It's not crazy, but the code here is doing it on every batched update regardless of if the user needs to know about it.

I really don't think I want to include this in core because it would be simple enough to install / write a utility that does this for you when you do need it. Is it too much to install an object diff function from NPM and use it with `this.props` and `prevProps`?

**Comment by trusktr** [comment]
> It is batched in terms of only happening after all set attribute calls happen in a microtask, but is called for every set.

Yep, exactly, 99.99999% of the time we only care about the final state, f.e. then we use the final state to determine what to render in the next animation frame in case of custom elements for rendering WebGL scenes.

> `array.includes()`

Oops, you're right. I originally meant to use of `Set`, which is mostly O(1) in v8 according to [this](https://stackoverflow.com/a/33614512/454780). Updated the PR. It's MUCH faster. Thought on this?

Here's an interesting benchmark you can run in the console that shows how much faster it is that Array with `.includes()`:

```js
var s = new Set
var NUM_ITERATIONS = 10000
var totalTime = 0
var begin

for (let i=0; i<NUM_ITERATIONS; i+=1) {
  begin = performance.now()
  if (!s.has(i)) s.add(i)
  totalTime += performance.now() - begin
}

console.log('total time', totalTime)
console.log('average time', totalTime/NUM_ITERATIONS)

totalTime = 0
s.clear()

for (let i=0; i<NUM_ITERATIONS; i+=1) {
  begin = performance.now()
  s.add(i)
  totalTime += performance.now() - begin
}

console.log('total time', totalTime)
console.log('average time', totalTime/NUM_ITERATIONS)

totalTime = 0
var a = []

for (let i=0; i<NUM_ITERATIONS; i+=1) {
  begin = performance.now()
  if (!a.includes(i)) a.push(i)
  totalTime += performance.now() - begin
}

console.log('total time', totalTime)
console.log('average time', totalTime/NUM_ITERATIONS)

totalTime = 0
a.length = 0

for (let i=0; i<NUM_ITERATIONS; i+=1) {
  begin = performance.now()
  a.push(i)
  totalTime += performance.now() - begin
}

console.log('total time', totalTime)
console.log('average time', totalTime/NUM_ITERATIONS)
```

> Is it too much to install an object diff function from NPM and use it with this.props and prevProps?

I didn't need to because writing one was easy. So my updated method looks like:

```js
        updated( prevProps, prevState ) {
            super.updated( prevProps, prevState )

            forChangedProps( this.props, prevProps, name => {
                this.vue_instance[ name ] = this[ name ]
            })
        }
```

Using the PR's new `Set` implementation, it'd look like this:

```js
        updated( prevProps, prevState, changedProps ) {
            super.updated( prevProps, prevState, changedProps )

            for (const prop of changedProps) {
                this.vue_instance[ prop ] = this[ prop ]
            }
        }
```

and it'll iterate quickly on only the number of props that were modified! Woot woot!!

**Comment by trusktr** [comment]
Here's a test that shows iterating on a Set is almost the same performance as iterating on an Array:

```js
var a = []
var s = new Set
var NUM = 1000000

for (let i=0; i<NUM; i+=1) a.push(i)
for (let i=0; i<NUM; i+=1) s.add(i)

var totalTime = 0

begin = performance.now()
for (let n of a) {
  n
}
totalTime += performance.now() - begin

console.log('total time', totalTime)

var totalTime = 0

begin = performance.now()
for (let n of s) {
  n
}
totalTime += performance.now() - begin

console.log('total time', totalTime)
```

So the Set implementation is very light for the convenience it offers. Still don't like it?

**Comment by trusktr** [comment]
Interesting, changing to `Set` somehow broke the lit renderer test?

**Comment by treshugart** [comment]
I fixed the lit-html issue causing the build failure last night. Pull and see if that fixes things for you.

**Comment by trusktr** [comment]
Looks like checks passed!

**Comment by treshugart** [comment]
> So the Set implementation is very light for the convenience it offers. Still don't like it?

It's not that I don't like it, it's more that I just don't think it's something that Skate should be concerned with. There's plenty of libraries out there that can give you a list of properties that are different between two objects.

I apologise and 100% value the ideas you bring to the table but I don't feel comfortable adding this feature without more people wanting it who can justify why this is hard to do out side of Skate. Cheers for the PR, though.

**Pull request closed without merging**
