### PR TITLE
fix(globals): do not share globals between skate versions

### LINKED ISSUE #493: Skate 0.13 and 0.12 use the same global namespace
They both use `window.__skate`, but they are not compatible in the way they store their lifecycle information (e.g. `created` string vs object). In order to fix 0.13 and 0.12, we need to backport https://github.com/skatejs/skatejs/blob/master/src/shared/vars.js

cc @seancurtis @jpnelson @treshugart

### PR DESCRIPTION
**Pull request by joscha**
This fixes #493 for 0.13.x

refs #495

@treshugart @jpnelson @seancurtis PTAL

### CODE REVIEW

**Comment by joscha** [comment]
tests are actually green - only karma dies afterwards, probably a build dep problem.

**Comment by joscha** [comment]
build fail was due to https://github.com/karma-runner/karma/issues/1782 - updated karma in order to get this green.

**Comment by jpnelson** [comment]
lgtm

**Comment by chrisdarroch** [comment]
I'm not terribly familiar with this part of the code, but... is the implication that skate will cease to create a window global? Or is it that a shared mutable state has been removed, and a `window.skate` global will still continue to exist once installing the library?

**Comment by joscha** [comment]
@chrisdarroch `window.skate` is not touched, only `window.__skate` which always has been internal.

**Comment by seancurtis** [comment]
Looks good

**Pull request merged**
