### PR TITLE
Fix spelling of "normalize" words

### PR DESCRIPTION
**Pull request by blikblum**
_If there is a linked issue, mention it here._

* [ ] Bug
* [ ] Feature

## Requirements

* [ ] Read the [contribution guidelines](https://github.com/skatejs/skatejs/blob/5.x/CONTRIBUTING.md).
* [ ] Wrote tests.
* [ ] Updated docs and upgrade instructions, if necessary.

## Rationale

Fixes spelling of normalize words. Notice that in some places already has the proper spelling

### CODE REVIEW

**Comment by treshugart** [comment]
I'm from California but live in Australia where this is the correct spelling 😛. If we think we should default to US spelling for everything, then I won't stop us from doing it.

**Comment by blikblum** [comment]
Not a big deal, but most programming projects i face use normalize, including big ones like:

React: https://github.com/facebook/react/search?q=normalize&unscoped_q=normalize
Polymer: https://github.com/Polymer/polymer/search?q=normalize&unscoped_q=normalize
Angular: https://github.com/angular/angular/search?q=normalize&unscoped_q=normalize

**Comment by treshugart** [comment]
Yeah, let's change it.

**Comment by treshugart** [comment]
I won't trigger a release since this doesn't really do much for consumers. Cheers for the consistency!

**Pull request merged**
