### PR TITLE
fix(typings): Match typings to 5.x API

### PR DESCRIPTION
**Pull request by freeman**
Temporary fix while waiting for a more complete revamp (see #1102)

### CODE REVIEW

**Comment by freeman** [comment]
@treshugart any issue with this PR, let me know if I need to change something.

**Comment by treshugart** [comment]
Thanks @freeman

**Comment by freeman** [comment]
Thanks to you @treshugart 

Would you mind doing an alpha release with this change ?

**Comment by treshugart** [comment]
Published 5.0.0-alpha.1 :)

**Pull request merged**
