### PR TITLE
chore: update skate build and npm scripts

### PR DESCRIPTION
**Pull request by nadiam84**

### CODE REVIEW

**Comment by treshugart** [comment]
lgtm

**Comment by lukebatchelor** [comment]
LGTM

**Comment by treshugart** [comment]
This isn't a "feat" it's a "chore". This will release a 1.3 and it has no impact on the public API. Pls fix.

**Comment by treshugart** [comment]
lgtm after commit is fixed

**Comment by treshugart** [comment]
lgtm

**Pull request merged**
