### PR TITLE
#501 - Modularise shared components.

### PR DESCRIPTION
**Pull request by treshugart**
Implements #501.

### CODE REVIEW

**Comment by joscha** [comment]
Not sure why that failed. It seems to work in #503

**Comment by treshugart** [comment]
Looks like it was a problem with the Sauce tunnel.

**Comment by joscha** [comment]
we should be able to delete `vars.js` I think?

**Comment by joscha** [comment]
LGTM

**Comment by joscha** [comment]
I think we need @jpnelson to add his LGTM, given that we both made changes...

**Comment by treshugart** [comment]
Good point @joscha, probably should delete the `vars.js`. @jpnelson what do you think about the performance implications here?

**Comment by joscha** [comment]
@treshugart - I removed it, however we need @jpnelson to review it :)

**Comment by treshugart** [comment]
Right, thanks @joscha, I hand't checked commits.

**Comment by treshugart** [comment]
lgtm

**Comment by joscha** [comment]
LGTM

**Pull request merged**
