### PR TITLE
#508 - Rename resolved to defined and add flag for rendered.

### PR DESCRIPTION
**Pull request by treshugart**
Implements #508.

### CODE REVIEW

**Comment by nadiam84** [comment]
We have styles that depend on "resolve" attribute, won't this affect them?

**Comment by treshugart** [comment]
@nadiam84 yeah we do. Unfortunately we're just going to have to update those. Since this is a change in the actual spec I'd rather stay as inline as we can at the cost of some selector renames.

**Comment by nadiam84** [comment]
if "resolved" transformed to "defined" then why
`if (render && !resolved) {`
transformed to
`if (render && !this.hasAttribute(renderedAttribute)) `
and not to this
`if (render && !this.hasAttribute(definedAttribute))`

**Comment by treshugart** [comment]
That was part of the issue; I think the third bullet point.

**Comment by nadiam84** [comment]
lgtm

**Comment by treshugart** [comment]
But that reminds me I don't think we need to add the rendered attribute, I
think we only need to check for its existence as a server renderer would
specifically add this after it renders it out.

**Pull request merged**
