### PR TITLE
Replace Saucelabs with Browserstack

### PR DESCRIPTION
**Pull request by bengummer**

### CODE REVIEW

**Comment by bengummer** [comment]
fyi @treshugart we'll need to add the `BROWSERSTACK_USERNAME` and `BROWSERSTACK_KEY` env values from https://www.browserstack.com/accounts/settings (Automate section) to https://travis-ci.org/skatejs/skatejs/settings

**Comment by treshugart** [comment]
Awesome! LGTM when you've added that stuff and it's green.

**Comment by bengummer** [comment]
Looks like Safari mobile is failing - not sure why, i'm going to try to reproduce the failure locally via iOS simulator.

**Comment by bengummer** [comment]
i've raised a PR on skatejs/build to run iOS first which should make this branch green - please 👍  https://github.com/skatejs/build/pull/270

**Comment by treshugart** [comment]
Woop sorry @bengummer I added a commit here for badge-size. Doesn't affect any thing so I'm just going to leave it. If the build goes 💚 I'll merge.

**Comment by treshugart** [comment]
There were some syntax errors; the v1 custom element polyfill requires lots of shims in order to work.

**Pull request merged**
