### PR TITLE
fix broken skate.prop permalink

### PR DESCRIPTION
**Pull request by marcoms**

### CODE REVIEW

**Comment by treshugart** [comment]
lgtm

**Comment by marcoms** [comment]
Odd - the lgtm check hasn't passed 🤔

**Comment by jpnelson** [comment]
lgtm

**Comment by treshugart** [comment]
Yeah not sure what's up with the lgtm plugin. I removed the maintainers file because we have the maintainers team. We should all be on it. I'll have a look.

**Comment by treshugart** [comment]
Looking at this now, we have a `properties` option and now the `prop()` function and namespace. Thinking that the former should become the latter for consistency. Maybe `props` so it's clear that you can define multiple props there.

The backstory in why the namespace was changed is:

1. `prop()` is now a function not just a namespace as it is a factory for creating a custom property type
2. it's easier to type and `prop` pretty much means `property` across the board

**Comment by marcoms** [comment]
I'm in favour of `skate.prop.*` (singular form reconciles well with enum naming schemes in languages like Rust) and the `props` option. For numerous properties it would definitely be more convenient.

**Pull request merged**
