### PR TITLE
chore(deps): add missing devdeps

### PR DESCRIPTION
**Pull request by stevemao**
Alternatively we could ask user to install them globally. But devdeps is probably better.

### CODE REVIEW

**Comment by treshugart** [comment]
Interesting. These weren't getting pulled in by [`skatejs-build`](https://github.com/skatejs/build)?

**Comment by stevemao** [comment]
I notice that I'm using npm v2, so this change should probably be discussed.

**Comment by treshugart** [comment]
Oh right. Try NPM 3. If that's the case we should try and enforce that in the package.json if we can.

**Comment by stevemao** [comment]
Oh yeah, if we purposely pull the deps from skatejs-build this is not needed.

**Pull request closed without merging**
