### PR TITLE
#742 - add support for webreflection/document-register-element

### PR DESCRIPTION
**Pull request by treshugart**
WIP: 

- [ ] Wait for skatejs/web-components#7 to be merged.
- [ ] Update tests testing class extension to not run in IE 9 and 10 since it doesn't support static property extension. Consumers supporting these browsers should use `.extends()` instead.
- [ ] Add IE9 and 10 to Browserstack.

Still retains support for native and the webcomponents.js v1 polyfill. Adds support for IE 9 and 10 mostly through just consuming the `document-register-element1` polyfill.

### CODE REVIEW

**Comment by jpnelson** [comment]
lgtm

will we test with both versions of skatejs-web-components?

**Comment by treshugart** [comment]
@jpnelson we probably should. I'll have a look at doing that. We really shouldn't *have* to, but document-register-element passes the element as an argument to the constructor in IE, I think, which requires us to write custom code for that. We could instead write a test for that integration point specifically, but might be better to just do both polyfills as you said.

**Comment by treshugart** [comment]
Merging as it seems the Browserstack build has finally passed.

**Comment by treshugart** [comment]
lgtm

**Pull request merged**
