### PR TITLE
Show how to update props on an instance

### PR DESCRIPTION
**Pull request by trusktr**
## Requirements

* [x] Read the
      [contribution guidelines](https://github.com/skatejs/skatejs/blob/5.x/CONTRIBUTING.md).
* [ ] Wrote tests.
* [x] Updated docs and upgrade instructions, if necessary.
* [ ] Updated TS definitions, if necessary.

## Rationale

_Why is this PR necessary?_

So people can better understand that updating instance props or attributes makes things automatically re-render.

### CODE REVIEW

**Comment by trusktr** [comment]
I think I did it right, but I am not able to successfully install dependencies to check.

**Comment by trusktr** [comment]
Oh, having yarn globally doesn't help. Looks like it isn't finding yarn locally for some reason:

```
⚡️   bolt v0.19.2 (node v8.5.0)
$ projector ./projector babel --envs es,esnext,node
/bin/sh: 1: node_modules/bolt/node_modules/.bin/yarn: not found
error Error
error     at ChildProcess.child.on.code (/home/trusktr/Downloads/src/skatejs+skatejs/node_modules/bolt/dist/modern/utils/processes.js:115:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! skatejs-monorepo@ prepare: `bolt build`
npm ERR! Exit status 1
```

**Comment by trusktr** [comment]
It looks like yarn is a dependency of bolt, yet it has that error. I'm on npm 5.6.0

**Comment by treshugart** [comment]
If you've changed NPM versions using NVM you'll have to re-install globally. Globally will work, that's how I have everything set up.

**Comment by treshugart** [comment]
You can also open the "show all checks" expander in the build status and click on the "details" thing to show the netlify build for this PR. Link: https://deploy-preview-1333--skatejs.netlify.com.

**Pull request merged**
