### PR TITLE
#666 - Support ref() callbacks passed as props

### PR DESCRIPTION
**Pull request by treshugart**
Implements #666.

### CODE REVIEW

**Comment by nadiam84** [comment]
Don't see any changes in the Readme.md file?

**Comment by nadiam84** [comment]
LGTM other than Readme.md file

**Comment by treshugart** [comment]
Nice catch, will update.

**Comment by treshugart** [comment]
This actually passes on iPhone. Sauce Labs is failing because of their infrastructure and I don't have an ETA, and we can't just wait for them, so merging.

**Pull request merged**
