### PR TITLE
fix(test): perf tests

### PR DESCRIPTION
**Pull request by joscha**
This fixes the performance tests and runs them automatically in our travis build.

### CODE REVIEW

**Comment by treshugart** [comment]
Noice.

**Comment by joscha** [comment]
uh wait, I think the tests are not green...

**Comment by joscha** [comment]
will look into the fix, seems to "works on my machine" :dancers:

**Comment by joscha** [comment]
Fixed in https://github.com/skatejs/build/pull/2 and ce0360f.

**Pull request merged**
