### PR TITLE
Try TypeScript

### PR DESCRIPTION
**Pull request by vvakame**
related #931

I tried to support TypeScript.
This is minimal implementation.
TypeScript has various super cool options, likes `--noImplicitAny`, `--strictNullChecks` and others.
But I made this change as small as possible.

Don't publish this code.
TypeScript users (it's me!) can't solved incremental-dom and window-or-global package definitions.
We should publish these definitions to [@types](https://www.npmjs.com/~types) and do `yarn add @types/incremental-dom @types/window-or-global`. (sure, I can do that!)

### CODE REVIEW

**Comment by treshugart** [comment]
Yeah publish those defs if you can! We can't just ignore the undeclared types for them, for now?

**Comment by treshugart** [comment]
@andreawyss this looks like it might overlap some of the work you've done in #938?

**Comment by vvakame** [comment]
> We can't just ignore the undeclared types for them, for now?

@treshugart yes. we should give a type hint for that.

TypeScript also provides easy means.
https://www.typescriptlang.org/docs/release-notes/typescript-2.0.html
see `Wildcard character in module names` section.

**Comment by treshugart** [comment]
Can you change the destination branch to the "typescript" branch, please? Unfortunately GitHub doesn't allow you to do this, so you'll have to resubmit the PR. Sorry :(

**Comment by vvakame** [comment]
done!
It supported in github from august. maybe...?
https://github.com/blog/2224-change-the-base-branch-of-a-pull-request

**Comment by treshugart** [comment]
Commented on your other PR, but just noting here, too, that we're revisiting the flow / ts decision https://github.com/skatejs/skatejs/issues/972. Will keep this open until that's done.

**Comment by treshugart** [comment]
I've decided we'll try TypeScript for the time being and assess again at a later point. Going to close this for now. Thanks again for all your hard work here, @vvakame, it's not in vain :)

**Pull request closed without merging**
