### PR TITLE
fix typo in README.md

### PR DESCRIPTION
**Pull request by vvakame**

### CODE REVIEW

**Comment by treshugart** [comment]
Hey @vvakame I know you've only modified the README, but your build is red. Maybe you just need to pull from master?

**Comment by vvakame** [comment]
I'm using a4ea5b424fd4dc0616322b113a012c63a8e6e5ba . it is a master/HEAD.
I think maybe master/HEAD is now broken... This respository does not have a npm-shrinkwrap.json.
Travis CI uses npm, not yarn.

**Comment by treshugart** [comment]
You're right. I thought I updated the Travis file. It should be all up to date now. Try pulling from master and then updating your branch.

**Comment by vvakame** [comment]
?? ◝(⁰▿⁰)◜ ??

**Comment by treshugart** [comment]
Thanks again @vvakame!

**Pull request merged**
