### PR TITLE
(fix:with polyfill) fixes Firefox and Safari

### PR DESCRIPTION
**Pull request by andreawyss**
This fixes Firefox and Safari.
May also help with IE too.

### CODE REVIEW

**Comment by andreawyss** [comment]
This is such small fix that I will merge it right away.

**Comment by Hotell** [comment]
what bug did it fix? It would be nice to have issue to every PR for further reference what did it solve

**Comment by Hotell** [comment]
also pls clean after yourself, when merged, delete the branch

**Comment by Hotell** [comment]
Last thing :D I dont know what conventions r u using within team @treshugart but IMHO it would be nice to get LGTM from one other member before merging anything, WDYT folks?

**Comment by andreawyss** [comment]
Yes, I agree but since this was such a small obvious one liner fix, I just when ahead and merged it.

constructor (...args) {
    super(...args);

@Hotell @treshugart If one forgets to forward the arguments received in the constructors to the super this will not work when Custom Element is polyfilled. We will need to add this in the documentation for the constructor to avoid users of the library to repeat this same mistake.
For this I have created #956.

**Comment by andreawyss** [comment]
@Hotell @treshugart It turns out that this was required by an older version of a polyfill.

**Comment by treshugart** [comment]
Yeah this was only a requirement for `document-register-element`. Might be best to remove it as we're not only officially documenting support for the `webcomponents` org polyfills and the consumer can just pull in `skatejs-web-components` and be done with it.

**Pull request merged**
