### PR TITLE
#321 - (Re-)implement template lifecycle callback as "render".

### PR DESCRIPTION
**Pull request by treshugart**
Implements #321. Will make it so that #319 will work and so that #320 can be updated to do the bare minimum of descending through a list of elements invoking the `template` callback on them if we find that's the best solution. At the very least, we have an opinionated mechanism for server-side rendering in that the `template` callback will not be called if the element is already resolved (already templated).

### CODE REVIEW

**Comment by alexreardon** [comment]
I am confused as to how this plays with the new `ready` callback

**Comment by treshugart** [comment]
The order with this will *always* be:

- `events`
- `properties`
- `created`
- `template`
- `callCreatedOnDescendants`
- `ready`

**Comment by alexreardon** [comment]
I am confused about the need for a 'template' function when we have `created` and `ready`. Also, naming it `template` might be misleading as we are now leaving it up to the developer when to template.

**Comment by treshugart** [comment]
Going to decline this for now. I don't think it's necessary at this point.

**Comment by treshugart** [comment]
Renamed `template` to `render` as it more clearly describes an action.

**Comment by treshugart** [comment]
I think this should be a thing because of the fact that it will only render if the element hasn't been `resolved` yet. Making users worry about this concern sucks if we can provide a specific hook for it that takes care if it.

**Pull request merged**
